name: sparsemodels_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.9
  - setuptools<65
  - numpy==1.25.2
  - libxcrypt
  - pip
  - r-base
  - r-essentials
  - r-rgcca
  - cython
  - rpy2
  - tqdm

